In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

In [ ]:
df=pd.read_csv('/content/medical_cost.csv')
df.head()

   Id  age     sex     bmi  children smoker     region      charges
0   1   19  female  27.900         0    yes  southwest  16884.92400
1   2   18    male  33.770         1     no  southeast   1725.55230
2   3   28    male  33.000         3     no  southeast   4449.46200
3   4   33    male  22.705         0     no  northwest  21984.47061
4   5   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df = df.drop(columns=['Id','region'])
df.shape

(1338, 6)

In [ ]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
charges     0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 62.8+ KB

In [ ]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [ ]:
#feature engineering
df['smoker'] = df['smoker'].map({'yes': 1, 'no': 0})

In [ ]:
df.sample(10)

      age     sex     bmi  children  smoker      charges
1192   58  female  32.395         1       0  13019.16105
833    58    male  34.390         0       0  11743.93410
1293   46    male  25.745         3       0   9301.89355
1109   45    male  20.350         3       0   8605.36150
802    21    male  22.300         1       0   2103.08000
378    64  female  30.115         3       0  16455.70785
317    54    male  32.775         0       0  10435.06525
343    63    male  36.765         0       0  13981.85035
1211   39    male  34.100         2       0  23563.01618
983    27  female  30.590         1       0  16796.41194

In [ ]:
df = df.drop(columns='sex')
df.shape

(1338, 5)

In [ ]:
# Prepare the data
X = df[['age', 'bmi', 'children', 'smoker']]
y = df['charges']

In [ ]:
# Split the data for train and test
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state=50)
print(X_train.shape)
print(X_test.shape)

(1070, 4)
(268, 4)

In [ ]:
# Fitting the model
lr_model = LinearRegression()
lr_model.fit(X_train,y_train)

LinearRegression()

In [ ]:
# Predict using test data
y_predict = lr_model.predict(X_test)
y_predict

array([ 8006.6966127 , 11661.14105581, 17245.89901012, 11282.92858129,
         433.14185864, 38728.99916608, 26216.5728887 ,  7747.21084863,
         820.55875406, 11535.5620035 ,  9273.4524188 , 32112.92983658,
        8172.35663107, 30866.29570727,  7601.23118546,  9490.2268413 ,
       11578.987719  ,  4735.50528083, 12326.37118117,  8650.25434057,
       -1300.51302513, 36566.23218274,  6683.20506819,  8828.04549254,
        4241.7307814 , 10924.53574683,  5405.55519996, 38058.08970644,
         616.80972085,   109.41173146, 37209.03503087,  4265.91158158,
       14463.00021936,  1360.6856817 ,  1273.21286518,  6111.00530298,
        9287.43603658,  1274.76919435, 11866.60328834, 39063.32729146,
        9766.9248815 ,  6748.50634778, 16917.88321704, 13262.48054542,
       35336.6711358 , 13945.64302041, 34104.71741292,  4494.24802141,
       12504.10424206,  9765.2931492 , 39910.59336457,  9453.89153158,
        6516.83085805, 37948.44535298, 11499.64482162, 35289.47647911,
       10915.51148093,  4073.02207751, 12158.5565508 , 13617.9465761 ,
       13524.09754556,  7316.62370475,  3586.62261747,  1857.96768246,
        9169.18536289, 10409.94259979,  5856.9202124 , 14075.24648096,
        5653.03189433, 15008.92854519, 14260.38947857,  5977.45881015,
        3712.07978805,  9789.07910639, 12079.47518435, 25490.8268356 ,
        8698.500032  ,  9434.40864342, 33560.80423207,  4891.98416314,
        3783.33915382, 27786.44352312,  1477.82134782, 14110.06605839,
        2141.37887075,  4158.26487889, 14187.27762862,  4753.94865564,
        2736.80718045,  2851.23091295,  3824.95307311, 11136.46681747,
        4240.69714977, 28781.79721064, 33562.75540423, 11104.4580438 ,
        9217.43096325, 10509.32588912, 25301.9789607 ,  3466.65892663,
        5934.38724967,   859.16449363, 36548.30562375, 12939.86542581,
       28572.63028299,  9872.82376079, 32405.68463955, 10373.82813304,
       10867.8406964 ,  8490.88934244,  8104.26801473, 10121.09602286,
        4938.31927931,  7302.06518006,  2725.09417468,  5126.44708071,
        7217.01975463, 11623.96976367, 16435.42688037, 32994.23732254,
        3392.63541787,  7321.80362635,  3437.85552646,  -474.30357247,
       12576.69330339, 10835.70976774,  7691.54942983, 11092.22822222,
       10795.03088318,  5703.54801562, 39856.84840276, 13078.95196807,
       37602.34613075, 16174.92479672, 29460.43595579, 33904.27271445,
       29580.55642571,  6928.68999351,  9544.97062849,  5048.30056683,
       13104.71247335,  4297.63026413,  4961.4432541 ,  5993.67226091,
        7796.85011736, 11496.8747969 ,  8354.07332112,  9314.52623743,
        6642.68884443,  6632.09075515, 34356.55526742,  6605.47668215,
        4170.57598533, 30755.29819124,  6033.3582018 , 11583.65082478,
        2923.94194711, 14995.89727419, 29623.4653254 , 14316.48633725,
       11978.71562977, 10823.63681631,  9110.2603884 , 10189.88151893,
        2870.71380111,  5988.61431213,  8678.27957615,  2709.49622772,
       30786.49417625,  2710.79120812, 34900.50913624,  2545.42734477,
       11211.65190349,  9025.59828456, 32674.39213656,  3841.00974479,
       34459.12661821, 10107.64662401, 29618.22722162, 12544.89921771,
       11634.28900998, 15557.62101402,  9233.96973558,  9449.54786566,
        6994.18855797, 36788.9472883 , 35523.58515057,  9345.22271866,
       32966.72890278,  8864.99630605,  6485.87302805, 31729.89729504,
        9203.88884923, 12569.60280652, 10416.73703273, 12810.76128687,
       32614.85165828,  5645.54067274,  2695.19326116, 30834.58299754,
       26032.19074363, 10733.51603898, 10498.61170873, 15274.74992639,
        8963.76390942, 27474.80393266,  9493.69365465, 13090.68825868,
       37090.70316341, 15488.57416918, 28346.05343   , 13429.33685621,
       11988.9942792 , 38972.60823129, 17593.27571855,  4359.1857963 ,
       13016.82152899,  9763.22000422, 30555.05675045,  1056.29915782,
        1126.0427913 , 32272.5735866 ,  6668.70481676,  5020.21144952,
        5034.51441608, 12407.09025273,  9660.60796545, 10690.50836023,
        4649.17066564, 10960.91156235, 30994.46490256,  5999.11353127,
       10443.71105139,  5608.32851046, 31818.26436725, 14465.85152893,
       12170.21155656,  9013.3278661 , 13297.10265582, 28407.76574125,
       16855.07330135,  7633.42002305,  5188.40333759, 15056.2972019 ,
        8235.8633354 , 11011.64852661, 26316.89691231,  7868.16748314,
        2485.01001392, 11823.13688487, 12747.19649145,  5482.51130314,
        8128.35012693, 10439.96557722, 13000.12597758, 12522.29214981,
       15122.37664608, 10058.44288625,  3980.15437814,  9046.21358341,
        7409.43322194, 15849.85909226, 12957.57720572,  4583.73010119,
        4434.00487276, 11401.61469486, 15968.66129693, 29967.63647815])

In [ ]:
# Predicted Score of train data
train_accuracy = lr_model.score(X_train, y_train)
train_accuracy

0.7393654059979747

In [ ]:
test_accuracy = lr_model.score(X_test, y_test)
test_accuracy

0.7842410709074031

In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

print('Mean absolute error = ', mean_absolute_error(y_test,y_predict))
print('Mean square error = ', mean_squared_error(y_test,y_predict))
print('R2 Score = ', r2_score(y_test,y_predict))

Mean absolute error =  3972.0995171524482
Mean square error =  34584351.96422181
R2 Score =  0.7842410709074031